[package]
name = "evmap"
version = "4.0.1"

description = "A lock-free, eventually consistent, concurrent multi-value map."
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

documentation = "https://docs.rs/evmap"
homepage = "https://github.com/jonhoo/rust-evmap"
repository = "https://github.com/jonhoo/rust-evmap.git"

keywords = ["map","multi-value","lock-free"]
categories = ["concurrency", "data-structures"]

license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "jonhoo/rust-evmap" }
maintenance = { status = "passively-maintained" }

[features]
nightly = ["hashbrown/nightly"]

[dependencies]
hashbrown = "0.1"
